services:
  - type: web
    name: perfect-prompt-sse
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:sse
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false